-- ========================================================
-- E-COMMERCE CUSTOMER BEHAVIOR ANALYSIS
-- PostgreSQL Queries for 10 Strategic Business Questions
-- Target Table: customer_shopping_behavior
-- ========================================================

-- Q1: Category-Level Revenue and AOV Breakdown
-- Identifying the highest-grossing categories and their average transaction value.
SELECT 
    "Category",
    COUNT(*) AS transactions,
    ROUND(SUM("Purchase Amount (USD)")::numeric, 2) AS total_revenue,
    ROUND(AVG("Purchase Amount (USD)")::numeric, 2) AS avg_order_value
FROM customer_shopping_behavior
GROUP BY "Category"
ORDER BY total_revenue DESC;


-- Q2: Performance Comparison: Subscribers vs. Non-Subscribers
-- Analyzing the impact of subscription status on overall spend and order value.
SELECT 
    "Subscription Status",
    COUNT(*) AS customers,
    ROUND(AVG("Purchase Amount (USD)"), 2) AS avg_order_value,
    ROUND(SUM("Purchase Amount (USD)"), 2) AS total_revenue,
    ROUND(100.0 * SUM("Purchase Amount (USD)") / SUM(SUM("Purchase Amount (USD)")) OVER (), 2) || '%' AS revenue_share
FROM customer_shopping_behavior
GROUP BY "Subscription Status"
ORDER BY total_revenue DESC;


-- Q3: Top 10 Regional Markets by Revenue and Subscription Rate
-- Finding the most lucrative states and their corresponding subscriber penetration.
SELECT 
    "Location",
    ROUND(SUM("Purchase Amount (USD)")::numeric, 2) AS total_revenue,
    ROUND(AVG("Purchase Amount (USD)")::numeric, 2) AS avg_purchase,
    COUNT(*) AS transactions,
    SUM(CASE WHEN "Subscription Status" = 'Yes' THEN 1 ELSE 0 END) AS subscribers,
    ROUND(100.0 * SUM(CASE WHEN "Subscription Status" = 'Yes' THEN 1 ELSE 0 END) / COUNT(*), 2) || '%' AS subscriber_rate
FROM customer_shopping_behavior
GROUP BY "Location"
ORDER BY total_revenue DESC
LIMIT 10;


-- Q4: The Effect of Promotional Discounts on Order Metrics
-- Evaluating how discount usage correlates with average order value and customer retention.
SELECT 
    "Discount Applied",
    COUNT(*) AS transactions,
    ROUND(AVG("Purchase Amount (USD)")::numeric, 2) AS avg_order_value,
    ROUND(AVG("Previous Purchases")::numeric, 2) AS avg_previous_purchases,
    ROUND(AVG("Review Rating")::numeric, 2) AS avg_rating
FROM customer_shopping_behavior
GROUP BY "Discount Applied"
ORDER BY avg_order_value DESC;


-- Q5: Most Popular Product Combinations
-- Discovering the highest revenue-generating combinations of season, category, color, and size.
SELECT 
    "Season",
    "Category",
    "Color",
    "Size",
    COUNT(*) AS units_sold,
    ROUND(SUM("Purchase Amount (USD)")::numeric, 2) AS total_revenue
FROM customer_shopping_behavior
GROUP BY "Season", "Category", "Color", "Size"
ORDER BY total_revenue DESC
LIMIT 15;


-- Q6: Spending Patterns by Age Demographic
-- Grouping customers by age brackets to determine the most valuable demographic.
SELECT 
    CASE 
        WHEN "Age" BETWEEN 18 AND 24 THEN '18-24'
        WHEN "Age" BETWEEN 25 AND 34 THEN '25-34'
        WHEN "Age" BETWEEN 35 AND 49 THEN '35-49'
        WHEN "Age" BETWEEN 50 AND 64 THEN '50-64'
        ELSE '65+' 
    END AS age_group,
    COUNT(*) AS customers,
    ROUND(AVG("Purchase Amount (USD)")::numeric, 2) AS avg_order_value,
    ROUND(SUM("Purchase Amount (USD)")::numeric, 2) AS total_revenue
FROM customer_shopping_behavior
GROUP BY age_group
ORDER BY total_revenue DESC;


-- Q7: Retention Analysis: First-Time vs. Returning Customers
-- Calculating the revenue share generated by repeat buyers versus new acquisitions.
SELECT 
    CASE 
        WHEN "Previous Purchases" > 0 THEN 'Repeat Customer'
        ELSE 'First-Time Buyer'
    END AS customer_type,
    
    COUNT(*) AS customer_count,
    
    ROUND(SUM("Purchase Amount (USD)")::numeric, 2) AS total_revenue,
    
    ROUND(AVG("Purchase Amount (USD)")::numeric, 2) AS avg_order_value,
    
    ROUND(100.0 * SUM("Purchase Amount (USD)") / 
          (SELECT SUM("Purchase Amount (USD)") FROM customer_shopping_behavior), 2) || '%' AS revenue_share
FROM customer_shopping_behavior
GROUP BY 
    CASE 
        WHEN "Previous Purchases" > 0 THEN 'Repeat Customer'
        ELSE 'First-Time Buyer'
    END
ORDER BY total_revenue DESC;


-- Analyzing the influence of purchase frequency on average order value.
SELECT 
    "Frequency of Purchases",
    COUNT(*) AS transactions,
    ROUND(AVG("Purchase Amount (USD)")::numeric, 2) AS aov
FROM customer_shopping_behavior
GROUP BY "Frequency of Purchases"
ORDER BY aov DESC;


-- Q8: Shipping Preferences and Customer Satisfaction
-- Examining how different shipping methods correlate with order value and review ratings.
SELECT 
    "Shipping Type",
    COUNT(*) AS orders,
    ROUND(AVG("Purchase Amount (USD)")::numeric, 2) AS avg_order_value,
    ROUND(AVG("Review Rating")::numeric, 2) AS avg_rating
FROM customer_shopping_behavior
GROUP BY "Shipping Type"
ORDER BY avg_order_value DESC;


-- Q9: Payment Method Trends and Spending Influence
-- Determining which payment options are associated with the highest transaction amounts.
SELECT 
    "Payment Method",
    COUNT(*) AS transactions,
    ROUND(AVG("Purchase Amount (USD)")::numeric, 2) AS avg_order_value,
    ROUND(SUM("Purchase Amount (USD)")::numeric, 2) AS total_revenue
FROM customer_shopping_behavior
GROUP BY "Payment Method"
ORDER BY avg_order_value DESC;

-- Q10: Revenue Contribution by ML-Generated Customer Segments
-- Breaking down sales metrics across the 4 distinct behavioral segments created in Python.
SELECT 
    "Segment Name" AS customer_segment,
    COUNT(*) AS customer_count,
    ROUND(AVG("Purchase Amount (USD)"), 2) AS avg_order_value,
	ROUND(AVG("Previous Purchases"), 2) AS avg_previous_purchases,
    ROUND(SUM("Purchase Amount (USD)"), 2) AS total_revenue,
    ROUND(100.0 * SUM("Purchase Amount (USD)") / SUM(SUM("Purchase Amount (USD)")) OVER (), 2) || '%' AS revenue_share
FROM customer_shopping_behavior
GROUP BY "Segment Name"
ORDER BY total_revenue DESC;

-- ========================================================
-- END OF ANALYSIS SCRIPT
-- ========================================================